### ISSUE TITLE
Issue in resizing the Image 

### ISSUE THREAD

**Issue by sreejith3534** [DCGM/B-MOD#1]
ValueError: Cannot feed value of shape (1, 6313, 5312, 3) for Tensor 'input_data:0', which has shape '(1, 48, ?, 3)'
I have seen function definition named **load_net** where you have specified the pixel height as 48 px , but even though after reshaping I'm getting error?
can you tell me how do you solved the problem of Image shaping?

**Comment by ikiss-fit** [comment]
The published networks are supposed to transcribe individual text lines 48 pixels high, not the entire pages. Such text lines can be downloaded at the B-MOD pages (https://pero.fit.vutbr.cz/brno_mobile_ocr_dataset).
